### ISSUE TITLE
Post-MVP thoughts.

### ISSUE THREAD

**Issue by cacraig** [18F/crime-data-api#175]
This issue exists to coagulate all of our steps beyond the MVP. 

- Improving DB/API performance.
- Adding additional endpoints.
- Additional filters.
- File export improvements.
- TODO

**Comment by harrisj** [comment]
I have a few Swagger steps that aren't really necessary for before the MVP:
- [ ] #184 Figure out a way to annotate Marshmallow schema fields with descriptions 
- [ ] #185 Denote that a Schema may include additionalProperties
- [ ] #186 Enumerate all fields that can be queried?

Our current Swagger is functional enough for testing, but it's not complete and correct. We would eventually need to fix these things above if we want the public to use our Swagger
