### ISSUE TITLE
Key ATO tasks and documentation to complete for March release 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#225]
This an epic for the tasks related to the core documentation we need to submit to obtain a 90-day ATO by the March timeline. Our goal is to submit these materials by the end of the year, so they will be an early focus of Sprint 2. 

Please see the issue in #infrastructure for more information: https://github.com/18F/Infrastructure/issues/750

**Comment by LarryBafundo** [comment]
Priority updates to this issue based on today's review with Holly & Jez: 

- [ ] Create a GSA LATO SSP based on the completed system-security-plan.yml file. Place that SSP into https://drive.google.com/drive/u/0/folders/0B8-KLfkQr4EVdHJqWXp5eFZmWTQ 
- [ ] Change leveraged authorization to the cloud.gov fedramp (though we don't have a link for that yet as it is hot off the press.)
- [ ] Increase detail of the system diagram, reference CALC2 diagram for level of detail required. This is included in the SSP.
 - [ ] Place any relavent security scan results into the ATO in progress folder, which will help shorten the ATO time overall.

Cc: @cacraig
