### ISSUE TITLE
Changes to denormalized NIBRS tables

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#655]
This issues replaces #639 and is going to be a parent issue for several issues of work.

The problem is our current denorm tables for NIBRS offender and victim collapse 1..many relationships of offender to offense (with location), victim to offense, and incident to property affected. In addition, they also prematurely reduce the many-to-many relationships between victim and offenders. This issue is going to contain a list of other issues that need to be resolved for this to be fixed:

- [ ] #656 Rework the `nibrs_offense_denorm` table
- [ ] #651 Rework offense/location/property (1..many relationships) inclusion in the `nibrs_offender_denorm`
- [ ] #657 Rebuild the `offender_counts_states`/`offender_counts_ori` table to correctly include all offenses
- [ ] Rebuild the `offense_offender_counts_states`/`offense_offender_counts_ori` tables to include all offenses
- [ ] #658 Rework offense/location/property/relationship (1..many) inclusion in the `nibrs_victim_denorm` table
- [ ] Create a new table for summarizing offender-victim relationships and possibly a new API endpoint
- [ ] #659 Rebuild the `victim_counts_states`/`victim_counts_ori` table to correctly include all offenses
- [ ] #660 Rebuild the `offense_victim_counts_states`/`offense_victim_counts_ori` tables to include all offenses
- [ ] #661 Rework the `offense_counts` table to support multiple weapons being used for an offense
- [ ] #662 Rework the `offense_offense_counts_states`/`offense_offense_counts_ori` tables to handle multiple weapon types being used for offenses.

This will be edited to include the issue numbers of related issues as well as progress made in solving them.

**Comment by harrisj** [comment]
In general we can see the same repeating themes in multiple of these issues I want to just highlight here. First, let's review

A single NIBRS incident:
Belongs to a single month/year of reporting for a single agency
Can have 0..many offenses (each with a location type)
Can have 0..many offenders (with codes for age, race type, ethnicity that must be dereferenced)
Can have 0..many victims (same demographic info, also a victim circumstance)
Can have 0..many properties associated with it (mapped to prop_type codes)
Can have 0..many weapons

In addition, there can be multiple relationships between offenders and victims

We want to pivot and instead look at NIBRS incidents from the perspective of offenders and victims (sometimes in the specific context of a single offense). For this, that means that certain fields like `offense_name` or `weapon_name` would actually have to support multiple values. There are several ways to do this in a table: delimited fields, multiple columns, multiple rows, but we could also just perhaps produce our API endpoints to handle the 1..many relationships between an offender and offenses and weapons and victims, etc.

**Comment by harrisj** [comment]
Closing since CJIS is taking over the generation of these views
